USE website;

-- LIMIT 1 : SELECTS ONLY THE FIRST EMPLOYEE WHO WORKS IN SOFTWARE DEV. DEPT 
SELECT * FROM STAFF WHERE department = 'Software Development' LIMIT 1;

-- ALTER TABLE : CAN CREATE, MODIFY OR DELETE COLUMNS
ALTER TABLE STAFF MODIFY department TEXT; -- CHANGES DATATYPE OF DEPT COLUMN FROM VARHCHAR(255) TO TEXT
ALTER TABLE STAFF CHANGE department Department TEXT;-- CHANGES NAME OF COLUMN
SELECT * FROM STAFF;
ALTER TABLE STAFF DROP Department;-- DELETES COLUMN

-- DROP
-- DROP TABLE table_name (DROPS TABLE)
-- DROP DATABASE database_name (DROPS DATBASE)
