USE STORE;
SHOW TABLES;

INSERT INTO VEGETABLES VALUES('Lettuce', 100, 1.65),('Carrot', 350, 1.9),('Pumpkin', 700, 2.5);

SELECT * FROM VEGETABLES WHERE PRICE BETWEEN 2 AND 3;

SELECT * FROM VEGETABLES WHERE WEIGHT < 400;
SELECT * FROM VEGETABLES WHERE name LIKE '%O' ORDER BY name DESC;